### ISSUE TITLE
001_basic.t hangs on WIndows

### ISSUE THREAD

**Issue by chorny** [karupanerura/p5-AnyEvent-ForkManager#2]
version 0.06

```
1..63
# start on_start
ok 1 - not working max
ok 2 - called by manager
# end   on_start
EV::child watchers not supported on this platform at C:/Strawberry201/perl/site/lib/AnyEvent/Impl/EV.pm line 75.
# Looks like you planned 63 tests but ran 2.
# Looks like your test exited with 255 just after 2.
ok 3 - called by child
(hangs)
```

**Comment by choroba** [comment]
I experimented with the module in Cygwin where it hangs, too. It seems the problem is [here](https://github.com/karupanerura/p5-AnyEvent-ForkManager/blob/master/t/001_basic.t#L28): the line never returns. I isolated the call to `manager_pid`, it returns correctly, so the real probem is `is` doesn't return.

**Comment by choroba** [comment]
OK, it seems the problem lies in Test::SharedFork. (https://github.com/tokuhirom/Test-SharedFork/blob/master/lib/Test/SharedFork/Store.pm#L104)[This line] gets stuck.

**Comment by choroba** [comment]
Adding

    use Time::HiRes qw{ usleep }; usleep 100;

before the line seems to fix the issue. There must be a race condition somewhere.

**Comment by karupanerura** [comment]
@choroba wow. Thank you for test!
But, I don't have Windows environment...
If you write patch, I'll merge it.

**Comment by choroba** [comment]
I changed Test::SharedFork, not your module. And adding a sleep is not a real solution. I'm still investigating.

**Comment by karupanerura** [comment]
ok. i understand.
