### ISSUE TITLE
Random test reports (t/002_blocking.t)

### ISSUE THREAD

**Issue by eserte** [karupanerura/p5-AnyEvent-ForkManager#7]
See http://matrix.cpantesters.org/?dist=AnyEvent-ForkManager%200.06 for an overview of test reports.

Statistical analysis does not show a pattern, except that 002_blocking.t may or may not fail: http://analysis.cpantesters.org/solved?distv=AnyEvent-ForkManager-0.06

**Comment by karupanerura** [comment]
thank you for your repoting!
It's fixed by: 72b675bbd9e3482d84ec388717b719190fb1a58c
